#!/bin/sh


if [ $# -eq 1 ]
 then
       fn=$1
else
      read fn
fi

if [ -f $fn ]
 then
	echo "The file exists "
else
        echo "The file does not exist"	
        exit 1
fi	
smth=2
res=0
res2=0
while read line
do
    isEven=`expr $smth % 2`
    if [ $isEven -ne 0 ]
    then
         for i in $line
         do 
              a=`expr $i % 2`
              if [ $a -eq 0 ]
              then
	      res=`expr $res + $i`
              fi
         done

    else
         for j in $line
         do
              a=`expr $j % 2`
              if [ $a -ne 0 ]
              then
	      res2=`expr $res2 + $j`
              fi
         done
    fi
    smth=`expr $smth + 1`
done < $fn
echo "the sum of the numbers in even lines = $res"
echo "the sum of the numbers in odd lines = $res2"